_BASE_: "../Base_det.yaml"

MODEL:
  META_ARCHITECTURE: "TransformerPureDetectorV2"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"

DATASETS:
  TRAIN: ("syntext1","syntext2",)
  TEST: ("totaltext_test",)

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (300000,)
  MAX_ITER: 350000
  CHECKPOINT_PERIOD: 1000

TEST:
  EVAL_PERIOD: 10000

OUTPUT_DIR: "output/R50/150k/pretrain"